{ config, pkgs, lib, ... }:
{
  # ============================================================================
  # EXAMPLE MACHINE CONFIGURATION TEMPLATE
  # ============================================================================
  #
  # This is a TEMPLATE for creating custom machine configurations.
  #
  # WHEN TO USE THIS:
  # - You want a custom hostname for your machine
  # - You need to import your hardware-configuration.nix from nixos-generate-config
  # - You want machine-specific settings (different users, custom modules, etc.)
  #
  # WHEN NOT TO USE THIS:
  # - First time installation: Use pre-built profiles directly like:
  #   nixos-install --flake /mnt/nixos-base#gnome-workstation
  # - Just testing desktops: Switch profiles with:
  #   sudo nixos-rebuild switch --flake .#kde-workstation
  #
  # HOW TO USE THIS TEMPLATE:
  # 1. Copy this file: cp machines/example-machine.nix machines/my-machine.nix
  # 2. Replace "hunter" with YOUR username throughout this file
  # 3. Copy home/hunter.nix to home/yourusername.nix and update it
  # 4. Import your hardware-configuration.nix (generated by nixos-generate-config)
  # 5. Add your machine to flake.nix:
  #    my-machine = mkSystem ./machines/my-machine.nix;
  # 6. Rebuild: sudo nixos-rebuild switch --flake .#my-machine
  #
  # ============================================================================

  imports = [
    ./configuration.nix
    ../profiles/cosmic.nix
    ../modules/common-users.nix
  ];

  # Machine-specific identity
  networking.hostName = "example-machine";

  # ============================================================================
  # USER CONFIGURATION
  # ============================================================================
  # 
  # ⚠️ CUSTOMIZE THIS: Replace "hunter" with YOUR username
  #
  # Steps to customize:
  # 1. Change "hunter" below to your username (e.g., "alice", "bob", etc.)
  # 2. Copy home/hunter.nix to home/yourusername.nix
  # 3. Update home-manager.users line below to match your username
  # 4. Set a REAL password after first boot: sudo passwd yourusername
  #
  # Example: a single "primary" user managed by both NixOS (account) and
  # Home Manager (dotfiles, packages, user services).
  machines.users = {
    hunter = {  # ☝ CHANGE THIS to your username
      isNormalUser = true;
      description = "Cameron Hunter";  # ☝ CHANGE THIS to your name
      extraGroups = [ "wheel" "networkmanager" ];

      # ⚠️ PASSWORD WARNING: This is intentionally empty for security!
      # You MUST set a password after installation:
      #   sudo passwd hunter  # (or your username)
      #
      # Or generate a hash and put it here:
      #   mkpasswd -m sha-512
      # Then: initialHashedPassword = "$6$rounds=...";
      initialHashedPassword = lib.mkDefault "";

      # 🔑 SSH KEYS (Recommended): For password-less login via SSH
      # Generate with: ssh-keygen -t ed25519 -C "your_email@example.com"
      # Then add your public key (~/.ssh/id_ed25519.pub) here:
      openssh.authorizedKeys.keys = [
        # "ssh-ed25519 AAAA...your-key-here... your_email@example.com"
      ];
    };
  };

  # 🏠 HOME MANAGER: Links your user config for dotfiles and user packages
  # ⚠️ CHANGE THIS: Replace "hunter" with your username in BOTH places

  home-manager.users.hunter = import ../home/hunter.nix;  # ☝ CHANGE "hunter" to match above

  # ============================================================================
  # HARDWARE CONFIGURATION
  # ============================================================================
  #
  # 🚨 CRITICAL: You MUST import your actual hardware configuration!
  #
  # Generate it with:
  #   nixos-generate-config --root /mnt
  #
  # This creates /mnt/etc/nixos/hardware-configuration.nix
  # Copy it to your nixos-base directory and uncomment the line below:
  #
  # imports = [
  #   ./hardware-configuration.nix  # ☝ UNCOMMENT THIS LINE
  # ];
  #
  # Without this, your system may not boot properly!
  # ============================================================================
}
